run_name: test

paths:
  train_data: "E:/OneDrive/Projects/programming/mf-lift/data/r_train.csv"
  val_data: "E:/OneDrive/Projects/programming/mf-lift/data/r_val.csv"
  test_data: "E:/OneDrive/Projects/programming/mf-lift/data/r_test.csv"
  pred_data: "E:/OneDrive/Projects/programming/mf-lift/data/r.csv"
  output_dir: outputs/

data:
  batch_size: 64
  num_workers: 0
  persistent_workers: False
  feature_cols: 
    - "Re"
    - "G1"
    - "ux_G1"
    - "uy_G1"
    - "G2"
    - "uxx_G2"
    - "uyy_G2"
    - "uxy_G2"
  target_cols: 
    - "logCL"
    - "nx"
    - "ny"

model: 
  hidden_layers: [256,128,64]
 
training:
  device: "cpu"
  batch_size: 32
  num_workers: 10
  max_epochs: 1
  learning_rate: 0.001
  lr_scheduler_patience: 20
  lr_scheduler_factor: 0.5
  early_stop_patience: 30